想买东西:
- htmlUrl: http://www.smzdm.com
  name: c5738f
  text: 什么值得买 | 优惠精选
  url: http://feed.smzdm.com
  filters:
    - type: include
      field: title
      keywords: ["可乐", "雪碧", "芬达", "柠檬", "茶叶", "纸巾", "酒精", "湿纸巾", "餐巾纸", "垃圾袋", "玩具", "水果", "拼多多", "鼠标"]
空闲的时候学会儿东西:
- htmlUrl: https://www.36kr.com/information/web_news
  name: 908fa3
  text: 36氪 | 互联网
  url: https://rsshub.dcts.top/36kr/information/web_news
  use_chatgpt: True
  filters:
    - type: include
      field: title
      keywords: ["美团", "阿里", "阿里巴巴", "百度", "特斯拉", "苹果", "Apple", "微软", "拼多多", "bilibili", "B站", "互联网", "字节跳动", "张一鸣", "王兴", "bytedance", "抖音", "腾讯"]
- htmlUrl: https://www.36kr.com/information/technology
  name: 392e02
  text: 36氪 | 科技
  url: https://rsshub.dcts.top/36kr/information/technology
  use_chatgpt: True
- htmlUrl: https://www.36kr.com/information/ccs
  name: b6bc94
  text: 36氪 | 财经
  url: https://rsshub.dcts.top/36kr/information/ccs
  filters:
    - type: exclude
      field: title
      keywords: ["VC", "李雪琴"]
  use_chatgpt: True
- htmlUrl: https://sspai.com/matrix
  name: 5270ca
  text: 少数派 | Matrix
  url: http://rsshub.app/sspai/matrix
  use_chatgpt: True
- htmlUrl: https://sspai.com/
  name: 7fc66f
  text: 少数派 | 推荐
  url: https://rsshub.app/sspai/index
  use_chatgpt: True
- htmlUrl: https://m.okjike.com/topics/63579abb6724cc583b9bba9a
  name: 9d9e0d
  text: 即刻 | AIGC
  url: https://rsshub.app/jike/topic/63579abb6724cc583b9bba9a
- htmlUrl: https://www.infoq.cn/topic/AI
  name: d9bca1
  text: InfoQ | AI
  url: https://rsshub.dcts.top/infoq/topic/AI
  use_chatgpt: True
- htmlUrl: http://www.ruanyifeng.com/blog/
  name: a120ad
  text: 阮一峰的网络日志
  url: http://feeds.feedburner.com/ruanyifeng
  use_chatgpt: True
- htmlUrl: https://hellogithub.com
  name: dad131
  text: HelloGithub
  url: https://hellogithub.com/rss
  use_chatgpt: True
- htmlUrl: https://app.daily.dev
  name: 213131
  text: DailyDiv
  url: https://app.daily.dev
  use_chatgpt: True
